# Generated by Django 5.2.4 on 2025-07-09 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='speaker',
            name='event',
        ),
        migrations.RemoveField(
            model_name='speaker',
            name='researcher',
        ),
        migrations.RemoveField(
            model_name='event',
            name='speakers',
        ),
        migrations.RemoveField(
            model_name='event',
            name='website',
        ),
        migrations.RemoveField(
            model_name='project',
            name='lead_researcher',
        ),
        migrations.RemoveField(
            model_name='project',
            name='repository',
        ),
        migrations.RemoveField(
            model_name='project',
            name='website',
        ),
        migrations.RemoveField(
            model_name='researcher',
            name='research_areas',
        ),
        migrations.RemoveField(
            model_name='talk',
            name='room',
        ),
        migrations.AddField(
            model_name='event',
            name='room',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='researcher',
            name='lab_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='researcher',
            name='lab_website',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='talk',
            name='additional_speakers',
            field=models.ManyToManyField(blank=True, related_name='additional_speakers', to='main.researcher'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='authors',
            field=models.CharField(help_text="Comma-separated list of authors in the format 'Lastname, Firstname.'", max_length=1000),
        ),
        migrations.AlterField(
            model_name='reference',
            name='reference_type',
            field=models.CharField(choices=[('paper', 'Paper'), ('book', 'Book'), ('thesis', 'Thesis'), ('preprint', 'Preprint'), ('journal_article', 'Journal Article'), ('conference_proceedings', 'Conference Proceedings'), ('book_chapter', 'Book Chapter'), ('other', 'Other')], max_length=40),
        ),
        migrations.AlterField(
            model_name='researcher',
            name='bio',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.DeleteModel(
            name='Organizer',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='Speaker',
        ),
    ]
