# Generated by Django 5.2.4 on 2025-07-09 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_profile_user_remove_speaker_event_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researcher',
            name='bio',
            field=models.TextField(blank=True, max_length=2000),
        ),
    ]
