# Generated by Django 5.2.4 on 2025-07-09 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_researcher_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='long_title',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='researcher',
            name='bio',
            field=models.TextField(blank=True, max_length=0),
        ),
    ]
