# Generated by Django 5.2.4 on 2025-07-09 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_researcher_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('workshop', 'Workshop'), ('tutorial', 'Tutorial'), ('special_session', 'Special Session'), ('session', 'Session'), ('conference', 'Conference'), ('meetup', 'Meet-up'), ('seminar', 'Seminar')], default='seminar', max_length=20),
        ),
    ]
