# Generated by Django 5.2.4 on 2025-07-09 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_event_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='talk',
            name='talk_type',
            field=models.CharField(choices=[('talk', 'Talk'), ('panel', 'Panel'), ('opening', 'Opening'), ('closing', 'Closing'), ('break', 'Break'), ('demo', 'Demo')], default='talk', max_length=20),
        ),
    ]
