# Generated by Django 5.2.4 on 2025-07-09 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_talk_talk_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='talk',
            name='references',
            field=models.ManyToManyField(blank=True, related_name='talks', to='main.reference'),
        ),
    ]
