# Generated by Django 5.2.4 on 2025-07-09 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_talk_references'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
