# Generated by Django 5.2.4 on 2025-07-10 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_delete_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='researcher',
            name='user',
        ),
    ]
